### PR TITLE
Review Request.

### PR DESCRIPTION
**Pull request by cod3smith**
This PR contains all the necessary commits for implementation of the bubble sort algorithm. This was accomplished by using loops to loops through the entire array, comparing the current array value with the next array value and switching positions if the current value is larger than the next one. This is repeated until the array is completely sorted.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, great job with this project :100: README is professional :100: PR is great, commit messages professional. We only need to implement 1 fix. Kindly check comments below:

- Let us create a separate file for bubble_sort.rb and bubble_sort_by.rb

Kindly fix this and submit another code review :slightly_smiling_face: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by lekegitrepo** [comment]
##### @KelynPNjeri and @umairarshadbutt, you have done a good job :+1:  by implementing the required changes. This project is approved.

##### _Reviewed by Temitayo Adeleke_.

**Review by lekegitrepo — APPROVED** [review]
##### Status: Approve

**Pull request merged**
